name: maplibre_gl
description: A Flutter plugin for integrating MapLibre Maps inside a Flutter application on Android, iOS and web platforms.
version: 0.22.0
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  maplibre_gl_platform_interface:
    git:
      url: https://github.com/will-maclean/flutter-maplibre-gl.git
      path: maplibre_gl_platform_interface
      ref: main

  maplibre_gl_web:
    git:
      url: https://github.com/will-maclean/flutter-maplibre-gl.git
      path: maplibre_gl_web
      ref: main

dev_dependencies:
  very_good_analysis: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.maplibre.maplibregl
        pluginClass: MapLibreMapsPlugin
      ios:
        pluginClass: MapLibreMapsPlugin
      web:
        default_package: maplibre_gl_web

platforms:
  android:
  ios:
  web:
